---
title: "Lebenslauf"
format:
  html:
    theme: cosmo
    page-layout: full
    css: ../styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
---
<!--::: {.resume-container}-->
::: {.rows}

## <i class="fas fa-briefcase"></i> Work Experience {.section-title}


::: {.experience-item}
<div class="item-header">
  <div><span class="item-title">Studentische Hilfskraft (Forschung)</span> <span class="item-company">| Fraunhofer IFAM.</span></div>
  <span class="item-date">July 2021 – July 2023</span>
</div>
- Python/C++ - Softwareentwicklung und Workflow-Automatisierung\
- Erstverarbeitung von Excel-Rohdaten mittels einer objektorientierten Skriptsprache (Python) sowie Automatisierung der Entwicklung
und des Testens des Workflows unter Verwendung der API PyAEDT [https://docs.pyansys.com](https://docs.pyansys.com) für Ansys-Software.\
- Verwendung von Python Bibliotheken wie Tkinter, NumPy, Matplotlib, Pandas, SciPy, Jupyter, Math, Fraction, PyAEDT usw.\
- Dokumentation und Aktualisierung des Steuerungsablaufdiagramms in Conceptboard\
- Entwicklung einer Python Tkinter GUI Anwendung, die die Bedienung für den Kunden erleichtert
- Detaillierte Dokumentation des Arbeitsablaufs im GitLab Issue Board.\
:::

::: {.experience-item}
<div class="item-header">
  <div><span class="item-title">Assistenz Systemingenieur</span> <span class="item-company">| TATA CONSULTANCY SERVICES Ltd.</span></div>
  <span class="item-date">July 2021 – July 2023</span>
</div>
- Entwicklung, Migration, Test und Deployment von Web-/Cloud-Anwendungen mit Python, C++, Java, GCP und Git\
- EDV-Kenntnisse mit Erfahrung in MS-Office und Linux\
:::

## <i class="fas fa-graduation-cap"></i> Ausbildung {.section-title}

::: {.edu-item}
**MSc. Electronics Engineering**  
*City-University of Applied Sciences Bremen, Germany (HSB)*  
<span class="item-date">2023 – 2026</span>  

**Abteilung:** Abteilung für Elektrotechnik und Informatik\
**Kursarbeit:** Grundlagen des maschinellen Lernens, Sprachmodul Deutsch, Intelligente Sensoren und Instrumentierung\
**Masterarbeit (in Bearbeitung)**: Maschinell unterstützte Co-Optimierung von Motorgeometrie und Hochfrequenz-Schaltparametern des
Wechselrichters für elektrische UAV-Antriebe
:::

::: {.edu-item}
**Batchelor of Technology Electrical and Electronics Engineering**  
*A P J ABDUL KALAM TECHNOLOGICAL UNIVERSITY (KTU)*  
<span class="item-date">2017 – 2021</span>  

**Kursarbeiten:** Elektrische Maschinen, Leistungselektronik und Regelungstechnik, Computerprogrammierung, Analyse elektrischer
Energiesysteme\
**Projekt:** Laststufenschalter für HVDC-Konvertertransformator\
:::


## <i class="fas fa-globe"></i> Languages {.section-title}

- Englisch (Muttersprache)
- Deutsch (Verhandlungssicher B1)



:::

::: {.col-md-8}

## <i class="fas fa-laptop-code"></i> Projects {.section-title}

::: {.project-item}
<div class="item-header">
  <div><span class="item-title">Plant App: Flutter/Dart Anwendungsentwicklung</span></div>
  <span class="item-date">Persönliches Projekt</span>
</div>
- Softwareentwicklung für Android, iOS und Webanwendungen unter Verwendung von Dart/Flutter für responsives Design
- Die Anwendung wurde dokumentiert und auf einer persönlichen, in Github gehosteten Website
bereitgestellt [https://ryanromeodev.github.io/Plant-App](https://ryanromeodev.github.io/Plant-App)
:::

::: {.project-item}
<div class="item-header">
  <div><span class="item-title">Persönliche Website: GitHub-Website</span></div>
  <span class="item-date">Persönliches Projekt</span>
</div>
Persönliche Website auf GitHub gehostet, um Fähigkeiten zu präsentieren : [https://ryanromeodev.github.io/resume/](https://ryanromeodev.github.io/resume/)
:::

::: {.project-item}
<div class="item-header">
  <div><span class="item-title">Entwurf und Implementierung eines universellen Biquad-Filters</span></div>
  <span class="item-date">Akademisch</span>
</div>
- Entwurf und Prüfung eines second-order Universal Active (Biquad) Filter
- Führen Sie Leiterplatten nahtlos vom Schaltplan über Layout, Validierung und Test bis hin zur einsatzbereiten Hardware.
- Detaillierte Dokumentation bereitgestellt : [https://ryanromeodev.github.io/hsb-amcd-sose2025-5/](https://ryanromeodev.github.io/hsb-amcd-sose2025-5/)
:::


## <i class="fas fa-cogs"></i> Fähigkeiten {.section-title}

::: {.skill-category}
**Technical**
<div class="skill-tags">
  <span class="skill-tag">Electrical Machines</span>
  <span class="skill-tag">Ansys Maxwell2D</span>
  <span class="skill-tag">PyAEDT</span>
  <span class="skill-tag">PCB Design</span>
  <span class="skill-tag">KiCAD</span>
</div>
:::

::: {.skill-category}
**Programming**
<div class="skill-tags">
  <span class="skill-tag">Python</span>
  <span class="skill-tag">Tkinter</span>
  <span class="skill-tag">C++</span>
  <span class="skill-tag">Flutter</span>
  <span class="skill-tag">Bash</span>
</div>
:::

::: {.skill-category}
**Data Science**
<div class="skill-tags">
  <span class="skill-tag">Pandas</span>
  <span class="skill-tag">Numpy</span>
  <span class="skill-tag">Scikit-learn</span>
  <span class="skill-tag">Regression and Curve Fitting</span>
</div>
:::

::: {.skill-category}
**Visualization and Documentation**
<div class="skill-tags">
  <span class="skill-tag">LaTeX</span>
  <span class="skill-tag">Matplotlib</span>
  <span class="skill-tag">Seaborn</span>
</div>
:::

::: {.skill-category}
**Tools & Platforms**
<div class="skill-tags">
  <span class="skill-tag">Git/GitLabs</span>
  <span class="skill-tag">Jupyter</span>
  <span class="skill-tag">VS Code</span>
</div>
:::

::: {.skill-category}
**Soft Skills**
<div class="skill-tags">
  <span class="skill-tag">Problem-solving</span>
  <span class="skill-tag">Analyytical Thinking</span>
  <span class="skill-tag">Result Oriented</span>
</div>
:::

:::
<!--:::-->