project:
  type: website
  output-dir: docs

website:
  title: "Ryan Romeo"
  favicon: images/favicon.ico
  page-navigation: true
  search: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

# Profile configuration
profile:
  default: en
  group:
    - [en, de]